### ISSUE TITLE
permissions of .jars

### ISSUE THREAD

**Issue by SolarAquarion** [PlayOnLinux/POL-POM-5#594] opened 2017-02-14 02:15 UTC
-rw------- 1 root root  445288 Feb 13 21:20 antlr-2.7.7.jar
-rw------- 1 root root    4467 Feb 13 21:20 aopalliance-1.0.jar
-rw------- 1 root root  501462 Feb 13 21:20 bcmail-jdk16-1.46.jar
-rw------- 1 root root  174074 Feb 13 21:20 bcpg-jdk16-1.46.jar
-rw------- 1 root root 1876535 Feb 13 21:20 bcprov-jdk16-1.46.jar
-rw-r--r-- 1 root root   38372 Feb 13 21:20 commandline-1.7.0.jar
-rw-r--r-- 1 root root  284184 Feb 13 21:20 commons-codec-1.10.jar
-rw------- 1 root root  378217 Feb 13 21:20 commons-compress-1.9.jar
-rw-r--r-- 1 root root  208700 Feb 13 21:20 commons-io-2.5.jar
-rw-r--r-- 1 root root  284220 Feb 13 21:20 commons-lang-2.6.jar
-rw-r--r-- 1 root root   61829 Feb 13 21:20 commons-logging-1.2.jar
-rw------- 1 root root  105169 Feb 13 21:20 compiler-0.9.0.jar
-rw------- 1 root root 2256213 Feb 13 21:20 guava-18.0.jar
-rw-r--r-- 1 root root   50894 Feb 13 21:20 jackson-annotations-2.7.0.jar
-rw-r--r-- 1 root root  252084 Feb 13 21:20 jackson-core-2.7.0.jar
-rw-r--r-- 1 root root 1198501 Feb 13 21:20 jackson-databind-2.7.0.jar
-rw------- 1 root root   53793 Feb 13 21:20 jgettext-0.14.jar
-rw------- 1 root root   45562 Feb 13 21:20 jmimemagic-0.1.2.jar
-rw-r--r-- 1 root root  350645 Feb 13 21:20 jsoup-1.10.2.jar
-rw------- 1 root root   65261 Feb 13 21:20 oro-2.0.8.jar
-rw-r--r-- 1 root root   38578 Feb 13 21:20 phoenicis-apps-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root   11507 Feb 13 21:20 phoenicis-cli-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root    9941 Feb 13 21:20 phoenicis-configuration-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root   43004 Feb 13 21:20 phoenicis-containers-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root    9608 Feb 13 21:20 phoenicis-engines-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root    7862 Feb 13 21:20 phoenicis-entities-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root 2004744 Feb 13 21:20 phoenicis-javafx-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root  109754 Feb 13 21:20 phoenicis-library-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root    6578 Feb 13 21:20 phoenicis-multithreading-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root   27665 Feb 13 21:20 phoenicis-scripts-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root    5636 Feb 13 21:20 phoenicis-settings-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root   67999 Feb 13 21:20 phoenicis-tools-5.0-SNAPSHOT.jar
-rw-r--r-- 1 root root   33148 Feb 13 21:20 phoenicis-win32-5.0-SNAPSHOT.jar
-rw------- 1 root root   40509 Feb 13 21:20 slf4j-api-1.7.16.jar
-rw-r--r-- 1 root root   10843 Feb 13 21:20 slf4j-simple-1.7.16.jar
-rw-r--r-- 1 root root  370067 Feb 13 21:20 spring-aop-4.2.5.RELEASE.jar
-rw-r--r-- 1 root root  731562 Feb 13 21:20 spring-beans-4.2.5.RELEASE.jar
-rw-r--r-- 1 root root 1096773 Feb 13 21:20 spring-context-4.2.5.RELEASE.jar
-rw-r--r-- 1 root root 1078771 Feb 13 21:20 spring-core-4.2.5.RELEASE.jar
-rw-r--r-- 1 root root  262988 Feb 13 21:20 spring-expression-4.2.5.RELEASE.jar
-rw------- 1 root root  895924 Feb 13 21:20 xercesImpl-2.4.0.jar
-rw------- 1 root root  109318 Feb 13 21:20 xml-apis-1.0.b2.jar
-rw------- 1 root root   78440 Feb 13 21:20 xmlParserAPIs-2.0.2.jar

where only the root user and read or write slf4j some people will be having issues launching it.  Why are certain scripts only root owner read/write while other jar's are owner read/write while everyone else can read it?

**Comment by plata** [comment] 2017-02-14 17:14
I cannot reproduce this behavior. I just compiled the current master with `mvn clean package` on Kubuntu 16.04 and all jars in phoenicis-dist/target have `-rw-rw-r--`. Are you compiling as root user?

**Comment by SolarAquarion** [comment] 2017-02-14 17:18
I use fakeroot thing

**Comment by plata** [comment] 2017-02-14 17:35
In this case I believe that it's not the responsibility of the build to set the file permissions (@qparis please correct me if I'm wrong). The permissions for our .deb build are set correctly by the maven plugin.
If you would build the package manually, `dh_fixperms` would do the job for you.

I have no idea how this is supposed to be done for AUR, but, in my opinion, this issue is an issue of building AUR and not of the Phoenicis build system.

**Comment by SolarAquarion** [comment] 2017-02-14 17:36
Makes sense kind of

**Comment by plata** [comment] 2017-02-14 17:41
I would propose that you ask someone at Arch who knows about AUR and close the issue here.

**Closed** 2017-02-14 18:08 UTC
