### ISSUE TITLE
Error when building POL 5

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#638] opened 2017-03-05 22:04 UTC
When I'm trying to build Play on Linux 5 with `mvn clean package`, I receive the following error:

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running org.phoenicis.win32.pe.PEReaderTest
> Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.121 sec - in org.phoenicis.win32.pe.PEReaderTest
> Running org.phoenicis.win32.registry.RegistryWriterTest
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec - in org.phoenicis.win32.registry.RegistryWriterTest
> Running org.phoenicis.win32.registry.RegistryParserTest
> Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.022 sec <<< FAILURE! - in org.phoenicis.win32.registry.RegistryParserTest
> testParse_realRegFile_testObjectPopulated(org.phoenicis.win32.registry.RegistryParserTest)  Time elapsed: 0.011 sec  <<< ERROR!
> java.lang.IllegalArgumentException: Error while parsing the registry
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at java.io.FileReader.<init>(FileReader.java:72)
> 	at org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:42)
> 	at org.phoenicis.win32.registry.RegistryParserTest.testParse_realRegFile_testObjectPopulated(RegistryParserTest.java:67)
> 
> Running org.phoenicis.win32.registry.RegistryKeyTest
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.phoenicis.win32.registry.RegistryKeyTest
> 
> Results :
> 
> Tests in error: 
>   RegistryParserTest.testParse_realRegFile_testObjectPopulated:67 » IllegalArgument
> 
> Tests run: 34, Failures: 0, Errors: 1, Skipped: 0

I've appended the full [log](https://github.com/PlayOnLinux/POL-POM-5/files/819787/build.txt).

I'm on commit 7d85b561b02aee77b5c66cac055c5bcfc00f0fd4

Just to tell a few details about my setup:

> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

> Apache Maven 3.3.9
> Maven home: /usr/share/maven
> Java version: 1.8.0_121, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-8-oracle/jre
> Default locale: de_DE, platform encoding: UTF-8
> OS name: "linux", version: "4.4.0-64-generic", arch: "amd64", family: "unix"

**Comment by plata** [comment] 2017-03-06 08:59
It is caused by `new FileReader(registryFile)` in `RegistryParser`. Can you debug the test to see what's going on (especially check the `registryFile`)?

**Comment by madoar** [comment] 2017-03-06 15:39
I'll try to debug it.
The first thing I'm noticing is, that when I try to import the phoenicis project, and its children projects, in eclipse I get the following `Discover m2e connectors` message:

>  No marketplace entries found to handle maven-java-formatter-plugin:0.4:format in Eclipse.  Please see Help for more information.

**Comment by madoar** [comment] 2017-03-06 15:51
Ok, seems like I've found the problem. 
My source code folder of POL 5 is located at `~/Dokumente/Play on Linux/POL-POM-5`, where I get the error, when I run `mvn clean package`.

If I copy `~/Dokumente/Play on Linux/POL-POM-5` to `~/Dokumente/POL-POM-5` (via `cp -r ~/Dokumente/Play\ on\ Linux/POL-POM-5 ~/Dokumente/POL-POM-5`) and run `mvn clean package` inside `~/Dokumente/POL-POM-5` it works. My guess is that the test can't find the `user.reg` file, because its path contains at least on space character, is this possible?

**Comment by plata** [comment] 2017-03-06 16:31
Approved. With spaces in the path I get:
```
Caused by: java.io.FileNotFoundException: /home/plata/POL%20POM%205/phoenicis-win32/target/test-classes/org/phoenicis/win32/registry/user.reg
```

**Comment by plata** [comment] 2017-03-06 16:43
Yep. The `getFile()` produces the `%20`.

Try to replace:
```Java
File registryFile = new File(this.getClass().getResource("user.reg").getFile());
```
by:
```Java
File registryFile = null;
try {
    registryFile = new File(this.getClass().getResource("user.reg").toURI());
} catch (URISyntaxException e) {
    e.printStackTrace();
}
```

**Comment by plata** [comment] 2017-03-06 16:51
Regarding the m2e problem: Maybe `maven-java-formatter-plugin` must be added to the m2e filter in pom.xml (like jacoco).

**Comment by madoar** [comment] 2017-03-06 16:54
After replacing the code with the given snipped, the previous error was fixed, but some later tests in tools are failing. My guess is for the same reason as the previous test.

**Comment by madoar** [comment] 2017-03-06 17:04
I've just tried to add the `maven-java-formatter-plugin` to the m2e filter, but it doesn't seem to be working.
What I've tried is to use the following in pom.xml:

```xml
<plugin>
	<groupId>org.eclipse.m2e</groupId>
	<artifactId>lifecycle-mapping</artifactId>
	<version>1.0.0</version>
	<configuration>
		<lifecycleMappingMetadata>
			<pluginExecutions>
				<pluginExecution>
					<pluginExecutionFilter>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<versionRange>[0.5,)
						</versionRange>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</pluginExecutionFilter>
					<action>
						<!-- m2e doesn't know what to do with jacoco, let's ignore it or annoying 
							error markers appear see http://wiki.eclipse.org/M2E_plugin_execution_not_covered -->
						<ignore></ignore>
					</action>
				</pluginExecution>
				<pluginExecution>
					<pluginExecutionFilter>
						<groupId>com.googlecode.maven-java-formatter-plugin</groupId>
						<artifactId>maven-java-formatter-plugin</artifactId>
						<versionRange>[0.4,)
						</versionRange>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</pluginExecutionFilter>
					<action>
						<!-- m2e doesn't know what to do with jacoco, let's ignore it or annoying 
							error markers appear see http://wiki.eclipse.org/M2E_plugin_execution_not_covered -->
						<ignore></ignore>
					</action>
				</pluginExecution>
			</pluginExecutions>
		</lifecycleMappingMetadata>
	</configuration>
</plugin>
```

**Comment by plata** [comment] 2017-03-06 17:07
Don't know then (not using eclipse myself). Maybe @qparis has an idea.

**Comment by plata** [comment] 2017-03-06 17:08
The issue with spaces in the path should be fixed by #639.

**Comment by madoar** [comment] 2017-03-07 11:52
Should I create a new issue for the m2e plugin warning/problem and close this issue?

**Comment by plata** [comment] 2017-03-07 12:07
Yes.

**Closed** 2017-03-07 14:42 UTC
