### ISSUE TITLE
Text needs to be wrapped and scaled

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#449] opened 2017-01-08 00:24 UTC
![bug](https://cloud.githubusercontent.com/assets/8126341/21746323/0738e784-d541-11e6-900a-5bd88dc1226c.png)
You can reproduce this by installing any Steam game.
(In case it isn't clear, I'm talking about the text)

**Comment by Brainzyy** [comment] 2017-01-08 12:32
Changing bug name as discussed in: https://github.com/PlayOnLinux/Scripts/pull/105

**Comment by plata** [comment] 2017-01-08 13:23
@Brainzyy should be fixed.

**Comment by Brainzyy** [comment] 2017-01-08 13:40
@plata It is fixed. But maybe one suggestion. In the message itself, maybe remove the \n so that you can see the full message. Because now you can't see it, no matter the dimensions.

**Comment by plata** [comment] 2017-01-08 14:44
@Brainzyy the problem is that the scroll pane is not resizing vertically. Can you try to add
```java
VBox.setVgrow(scrollPane, Priority.ALWAYS);
```
to StepRepresentationMessage `drawStepContent()` and see if you prefer that?

**Comment by Brainzyy** [comment] 2017-01-08 15:15
@plata That is perfect. The ScrollPane is not there anymore and the text scales perfectly with the resolution of the window.

**Comment by plata** [comment] 2017-01-08 15:18
@Brainzyy there's only one thing I don't like about this: The spinning wheel is no longer centered. But I cannot find a way to fix that.

Can you create a pull request?

**Comment by Brainzyy** [comment] 2017-01-08 15:23
@plata I can make a PR for the suggestion you made. But I'm not experienced enough with Java to figure out the spinning wheel center thing. I'll open a PR and see what @qparis his opinion is.

**Closed** 2017-01-08 15:31 UTC
