### ISSUE TITLE
Only 9 apps are displayed

### ISSUE THREAD

**Issue by ImperatorS79** [PlayOnLinux/POL-POM-5#957] opened 2017-07-23 12:33 UTC
Even with my personal git repo, only five apps are displayed instead of all the apps that are on the repo. I don't see what I have done wrong, since building POL5 was done flawlessly.
![only 5 apps](https://user-images.githubusercontent.com/19779882/28499346-d2f1b3b2-6fb3-11e7-9fb1-67e62e3d73e3.png)

**Comment by madoar** [comment] 2017-07-23 12:39
Can you please start POL 5 via terminal and tell us if you get any errors?

**Comment by ImperatorS79** [comment] 2017-07-23 12:58
Here it is
[log.txt](https://github.com/PlayOnLinux/POL-POM-5/files/1168083/log.txt)

**Comment by madoar** [comment] 2017-07-23 13:00
Can you please take a look inside the folder `/home/fevrier/.Phoenicis/cache/git1703867752` and tell us what it contains?

**Comment by ImperatorS79** [comment] 2017-07-23 13:03
![cache phoenicis](https://user-images.githubusercontent.com/19779882/28499507-0a43b51e-6fb8-11e7-8618-0ea3ef57e212.png)
![cache phoenicis 2](https://user-images.githubusercontent.com/19779882/28499508-0b11fed8-6fb8-11e7-80f7-0e486f5b97c5.png)

**Comment by ImperatorS79** [comment] 2017-07-23 13:03
Seems to contain the right files

**Comment by plata** [comment] 2017-07-23 13:06
Same behavior if you clone the repository manually and add it as local folder?

**Comment by ImperatorS79** [comment] 2017-07-23 13:10
Seems the apps tab is not updating itself

**Comment by plata** [comment] 2017-07-23 13:10
Why?

**Comment by plata** [comment] 2017-07-23 13:13
Sorry, I don't quite understand. What exactly does not change and is supposed to change?

**Comment by ImperatorS79** [comment] 2017-07-23 13:15
The app tab is still displaying the 9 apps

**Comment by plata** [comment] 2017-07-23 13:16
How does your repositories.json look like?

**Comment by ImperatorS79** [comment] 2017-07-23 13:17
If you are speaking about the file inside .Phoenicis, 

[{"type":"git","gitRepositoryUri":"https://github.com/PlayOnLinux/Scripts","branch":"master"},{"type":"git","gitRepositoryUri":"https://github.com/PlayOnLinux/Oldwares","branch":"master"},{"packagePath":"/org/phoenicis/repository","type":"classpath"},{"repositoryLocation":"/home/fevrier/POL5/Sc

**Comment by plata** [comment] 2017-07-23 13:18
Is that complete? Looks somewhat broken at the end.

**Comment by ImperatorS79** [comment] 2017-07-23 13:19
I forgot the end sorry

**Comment by plata** [comment] 2017-07-23 13:24
Mh. I just tried the same config (without the "local" one of course) and it works fine on my machine. Do you know how to debug?

**Comment by ImperatorS79** [comment] 2017-07-23 13:25
No, sorry

**Comment by plata** [comment] 2017-07-23 13:28
Ok. I have to admit that I'm a bit clueless at the moment why this is happening because I cannot reproduce it. It's especially strange that it shows some of the applications (i.e. everything apart from games).

I can only suggest some things you could try out so we might get an idea what's going on.

**Comment by plata** [comment] 2017-07-23 13:28
Can you copy + paste one folder from "Games" to e.g. "Development" and see if it shows up?

**Comment by ImperatorS79** [comment] 2017-07-23 13:30
I tried with AC2, and AC2 is now displayed with the 9 other apps

**Comment by plata** [comment] 2017-07-23 13:32
How does your Games/category.json look like?

It should be:
```
{
	"name": "Games",
	"type": "INSTALLERS"
}
```

**Comment by ImperatorS79** [comment] 2017-07-23 13:33
Exactly like that

**Comment by plata** [comment] 2017-07-23 13:35
Ok. If you copy everything from "Games" into "Development", does it work?

**Comment by ImperatorS79** [comment] 2017-07-23 13:38
All those games seems to be displayed, but some of the Star Wars (and maybe others) games aren't (for example : SW Jedi Knight)

**Comment by plata** [comment] 2017-07-23 13:39
Could it be that there is an issue with ":" etc. in folder names?

**Comment by ImperatorS79** [comment] 2017-07-23 13:42
For the Jedi Knight games, it's a -, not a : 
Dark forces use a : and is displyed

**Comment by plata** [comment] 2017-07-23 13:44
E.g. "STAR WARS Jedi Knight - Jedi Academy" is "testing" so unless you checked the "testing" checkbox, you will not see it. Can your verify that you see everything with "testing" checked?

**Comment by ImperatorS79** [comment] 2017-07-23 13:45
SW jedi knight doesn't appear with "testing" checked, but some games appear

**Comment by plata** [comment] 2017-07-23 13:46
Which system are your using (Mac/Linux)?

**Comment by ImperatorS79** [comment] 2017-07-23 13:46
Ubuntu 17.04

**Comment by plata** [comment] 2017-07-23 13:48
Ok. That explains it. One second. I'll fix something.

**Comment by plata** [comment] 2017-07-23 13:55
The issue with Jedi Knight should be fixed in PlayOnLinux/Scripts#300.

However, this doesn't explain why the "Games" folder is not working.
I would like to see if it is related to the name or to the folder itself. Can you rename "Development" to "Games"?

**Comment by chriamue** [comment] 2017-07-23 14:01
I changed Development to Games and also changed it in its category.json file and Notepad++ is not visible anymore.
I renamed Games to Games2 and changed the category.json file and the games are back.
It's a problem with the name.

**Comment by ImperatorS79** [comment] 2017-07-23 14:02
I changed games to chocolat and category.json and it works now

**Comment by chriamue** [comment] 2017-07-23 14:11
The problem is the category name of Internet.
Maybe two categories of the same name from two different repositories can be merged but not two folder from same repository.

**Comment by ImperatorS79** [comment] 2017-07-23 14:21
Effectively

**Comment by plata** [comment] 2017-07-23 14:25
Makes sense. No idea how that could happen but I just figured out that I'm missing the stuff from "Internet". So probably my directory is walked in a different order than yours and therefore I still have the games.

**Closed** 2017-07-23 14:26 UTC
