### ISSUE TITLE
Cancel button not fully visible

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#754] opened 2017-05-04 01:12 UTC
The cancel button on an install wizard should be fully visible, most applications don't shorten it in this way. I don't know what you'd actually need to do to fix this, maybe lengthen both buttons?
![screenshot from 2017-05-04 02-10-41](https://cloud.githubusercontent.com/assets/3178485/25687534/180a7d6e-306f-11e7-9f06-f040c34fcd48.png)
![screenshot from 2017-05-04 02-12-26](https://cloud.githubusercontent.com/assets/3178485/25687541/2303c536-306f-11e7-85d6-cc9cef9c9e63.png)

**Comment by qparis** [comment] 2017-05-04 21:46
Yes we need to lengthen the two buttons :) 
You can also reduce the size of the text

**Comment by madoar** [comment] 2017-05-04 21:53
I think the best way to do is to make the button size fit to its content.
We should do this to enable an easy scaling of the components.

**Comment by plata** [comment] 2017-05-05 18:01
@madoar how did you do this? I cannot reproduce the behavior.

**Comment by madoar** [comment] 2017-05-05 18:04
That's a good point.
I can't reproduce this either...

**Comment by madoar** [comment] 2017-05-06 21:34
@Ads20000 can you tell us what commit you used to build POL 5, if this only happens with the default theme and in case you already use a commit that enables you to scale the gui in the settings, what scale setting you've used?

**Comment by Ads20000** [comment] 2017-05-06 21:39
@madoar Looking at the commit dates I'm assuming [1b993fb877a168bf0eb4f7200b015304f8ba0997](https://github.com/PlayOnLinux/POL-POM-5/commit/1b993fb877a168bf0eb4f7200b015304f8ba0997) since that's when I reported this and I'm pretty sure I reported it straight after a fresh `git clone`.

`git pull ; mvn clean package` works fine for updating right? Can try the latest commit doing that?

**Comment by madoar** [comment] 2017-05-06 21:46
`git pull`
`mvn clean package` 
should work for updating the application files.

It seems like the commit you've used already contains a part of the scaling support.
Therefore it would be nice if you could check two things:

1. Please check if it works with the most current commit, because we've changed some things.
2. Play a little with the "Scale the user interface" slider in the `User Interface` settings, to check if this changes the button size and/or solves the problem. If this is the case it would be nice to know which position starts to make problems.

**Comment by Ads20000** [comment] 2017-05-06 22:13
@madoar Same problem with the most current commit.
This setting works
![screenshot from 2017-05-06 23-12-16](https://cloud.githubusercontent.com/assets/3178485/25776256/8385832e-32b1-11e7-801c-2e613b508f58.png)
This setting doesn't
![screenshot from 2017-05-06 23-12-33](https://cloud.githubusercontent.com/assets/3178485/25776259/9216a896-32b1-11e7-8016-5e4fa38a7b41.png)

**Comment by plata** [comment] 2017-05-07 08:53
@madoar maybe #760 helps? If you could merge the commits (#760 - #763) which fix the themes @Ads20000 could try again.

**Comment by plata** [comment] 2017-05-21 09:59
@Ads20000 closing this as neither me not @madoar could reproduce it and the styles have been updated. If you can reproduce the issue with the current master, please re-open this issue.

**Closed by plata** 2017-05-21 09:59 UTC
