### ISSUE TITLE
Illegal URI characters in game paths

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#796] opened 2017-05-17 08:43 UTC
Some games contain illegal characters in their path, which can make it impossible or at least hard to shown images from their corresponding folders.
An example for this is Assassin's Creed Revelations:
![grafik](https://cloud.githubusercontent.com/assets/18488086/26145661/86775dd4-3aed-11e7-8aaa-73cbdaea5f9f.png)
On the screenshot you'll see, that the miniature in the right details view isn't shown.
The reason becomes apparent if you take a look at the terminal output:
```
WARNUNG: CSS Error parsing '*{-fx-background-image: url('file:/home/marc/.Phoenicis/cache/git1476132144/Games/Assassin's%20Creed%20Revelations/miniatures/main.png');}: Unexpected token 'file:/home/marc/.Phoenicis/cache/git1476132144/Games/Assassin' at [1,24]
```

**Comment by plata** [comment] 2017-05-17 15:49
This is a duplicate of PlayOnLinux/Scripts#229.

**Comment by plata** [comment] 2017-05-21 10:17
@madoar do you also watch the scripts repository? I have this and some other PRs there which should be reviewed.

**Comment by madoar** [comment] 2017-05-21 10:21
I don't watch it, because I'm not an expert at writing script. I would love to review the scripts but I don't have the rights for that in the Scripts repository.

**Comment by plata** [comment] 2017-05-21 10:24
@qparis could you please give @madoar the rights for the Scripts repository?

@madoar I would appreciate if you could also watch it. Currently there's not a lot going on but that should change soon. Then it would be nice to have some people who can approve scripts which are submitted.

**Comment by madoar** [comment] 2017-05-21 10:41
Ok, I'm watching the Scripts repository now.

**Comment by plata** [comment] 2017-05-21 10:47
Thanks. I have the rights to merge there without review so you can just leave a comment if it's ok or not (didn't want to merge without someone at least have a look at it).

**Comment by madoar** [comment] 2017-05-22 10:25
@plata to close this issue we'll still need to rename the folders in the Scripts repository to not contain "illegal" characters (like `'`).

**Closed** 2017-05-22 16:12 UTC
