### ISSUE TITLE
error main class com.playonlinux.app.PlayOnLinuxApp

### ISSUE THREAD

**Issue by andykimpe** [PlayOnLinux/POL-POM-5#297] opened 2015-12-23 01:05 UTC
build on archlinux using branch master

build 100% work no error

starting error

Error: Can not find or load the main class com.playonlinux.app.PlayOnLinuxApp

it would be possible to have a functional version beta please

or a version compiled

or a version that is already compiled

Thank you

**Comment by qparis** [comment] 2015-12-23 01:08
https://github.com/PlayOnLinux/POL-POM-5/pull/298 should fix the issue.
However, please note that PlayOnLinux 5 is far from being stable at the moment.

**Comment by andykimpe** [comment] 2015-12-23 13:24
compilation error

view log on pastebin

http://pastebin.com/UdYpuiYr

**Comment by Tomahna** [comment] 2015-12-23 14:30
I've been unable to reproduce your test failure. Can you give us more informations on what you're using, java/maven version and whether it is the oracle or openJDK ? Anyway you can skip maven tests with the -DskipTests=true option.

You're problem is probably due to the fact that POL5 don't have a proper packaging at the moment. To launch it you must either
- get all the subproject's jar in you're java classpath (java -cp)
- launch it from an ide (In eclipse : Run as application on PlayOnLinuxApp in the phoenicis-app project)

**Comment by andykimpe** [comment] 2015-12-23 15:41
http://wiki.playonlinux.com/index.php/Building_PlayOnLinux_5

jus execut on arlinux build 01-12-2015 (latest) i686

with archlinuxfr repository activated

yaourt -S maven  jdk8-openjdk java-openjfx gradle git

cd

rm -rf POL-POM-5

git clone https://github.com/PlayOnLinux/POL-POM-5

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"

cd POL-POM-5

mvn assembly:assembly

**Comment by Tomahna** [comment] 2015-12-23 16:26
It seems that the wiki isn't up to date. Actually the packaging was broken. #300 should partly fix your problem.

While it isn't merged you can test it by cloning it from my repository : 
- git clone -b Assembly https://github.com/Tomahna/POL-POM-5.git
- cd POL-POM-5
- mvn clean package (with -DskipTests if you still have test failures)
- cd phoenicis-dist/target
- unzip phoenicis-dist.zip
- cd phoenicis-dist
- ./PlayOnLinux.sh

**Comment by Tomahna** [comment] 2015-12-24 13:26
Pull Request has been merged, you should be able to package PlayOnLinux from this repository now.

**Comment by ProfessorKaos64** [comment] 2016-11-18 17:24
I did not see this, so I had a duplicate post #329.  

I picked up and adopted the AUR package, however, I have trouble with running the application. It appears the contents of `phoenicis-dist/` (i.e. `lib/*`) is not enough to run the application, as it fails to find the classes, usually located in `phoenicis-app/target/classes`.

```
Error: could not find or load main class com.playonlinux.app.PlayOnLinuxApp
```

What location does classes need to go? Missing files?

See: https://aur.archlinux.org/packages/playonlinux5-git/

**Comment by ProfessorKaos64** [comment] 2016-11-18 18:37
I would be nice if the script did a little footwork to ensure Java 8 is used. On Arch Linux, Java 7 and Java 8 can co-exists, and users shouldn't be forced to set everything default to Java 8. This section from their [wiki](https://wiki.archlinux.org/index.php/java#Launching_an_application_with_the_non-default_java_version) works well:

```
export PATH=/usr/lib/jvm/java-8-openjdk/jre/bin/:$PATH
```

Resulting in

```
POL_HOME=$(dirname $0)
CLASSPATH=${CLASSPATH}:$POL_HOME/lib/*

# Ensure path of Java 8 takes precedence on systems with Java 7 and 8 both installed
# This is non-destructive and does not force users to set the default java env to Java 8
export PATH=/usr/lib/jvm/java-8-openjdk/jre/bin/:$PATH

java -classpath "$CLASSPATH" com.playonlinux.app.PlayOnLinuxApp "$@"
```

**Closed** 2016-12-22 23:29 UTC
