### ISSUE TITLE
Wine cannot find the ncurses library (libncurses.so.5)

### ISSUE THREAD

**Issue by ycmjason** [PlayOnLinux/POL-POM-5#772] opened 2017-05-06 13:12 UTC
This happens when I want to run the game.

```
Wine cannot find the ncurses library (libncurses.so.5).
```

Sorry, it's me again. Any idea how to fix this? I seem to have libncurses.so.6 instead of 5.

Note: I am on archlinux.

**Comment by madoar** [comment] 2017-05-06 13:26
When exactly do you get this error?
@plata, I think you're more knowledgeable about this.

**Comment by ycmjason** [comment] 2017-05-06 14:19
I am trying to run league client. :(

**Comment by plata** [comment] 2017-05-06 16:36
I don't know for arch but for Ubuntu this is a duplicate of #741. I guess you just have to install libncurses 5.

**Comment by plata** [comment] 2017-05-08 16:25
duplicate of #643

**Closed by plata** 2017-05-08 16:25 UTC
